{
 "title": "Sensei Metrics",
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(sensei_user_id) FROM sensei_users LIMIT 50 "
    }
   ]
  },
  {
   "title": "Signups by Day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "select date(joined_at) as join_date, count(*) as new_users\nfrom sensei_users \nwhere joined_at >= now() - interval '168 hours'\ngroup by date(joined_at)\norder by date(joined_at)"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH daily_counts AS (\n    SELECT \n        DATE_TRUNC('day', joined_at) AS joined_date,\n        COUNT(*) AS daily_count\n    FROM sensei_users\n    GROUP BY DATE_TRUNC('day', joined_at)\n),\nrunning_totals AS (\n    SELECT \n        joined_date,\n        daily_count,\n        SUM(daily_count) OVER (ORDER BY joined_date) AS running_total\n    FROM daily_counts\n)\nSELECT date(joined_date) as join_date, running_total\nFROM running_totals\nWHERE joined_date >= NOW() - INTERVAL '21 days'\nORDER BY joined_date;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH user_days AS (\n    SELECT \n        sensei_user_id,\n        COUNT(DISTINCT DATE(event_timestamp)) AS days_with_events\n    FROM \n        events\n    GROUP BY \n        sensei_user_id\n)\nSELECT \n    days_with_events,\n    COUNT(sensei_user_id) AS user_count\nFROM \n    user_days\nGROUP BY \n    days_with_events\nORDER BY \n    days_with_events;"
    }
   ]
  },
  { "title": "Locations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "geomap",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (lat, lon, city_name, country_name) (\n  count_over_time({instance=\"ingress-nginx-external\"} \n  | json \n  | lat != \"\"\n  | vhost =~ `senseichess.com`\n  |__error__=``[$__range])\n) > 20",
     "legendFormat": "{{ip_address}}"
    }
   ]
  },
  {
   "title": "Requests by Location",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (city_name, country_code) (count_over_time({instance=\"ingress-nginx-external\"} | json | city_name != \"\" | vhost =~ `senseichess.com` |  __error__=\"\" [24h]))",
     "legendFormat": "{{city_name}} {{country_code}}"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Queued",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) job_status from job_queue  where job_status = 'queued'"
    }
   ]
  },
  {
   "title": "Queued",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) job_status from job_queue  where job_status = 'processing'"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) job_status from job_queue  where job_status = 'completed'"
    }
   ]
  },
  {
   "title": "Job Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select \njob_type, \ncount(*) filter (where job_status = 'queued') as queued,\ncount(*) filter (where job_status = 'processing') as processing,\ncount(*) filter (where job_status = 'completed') as completed,\ncount(*) filter (where job_status = 'failed') as failed\nfrom job_queue \ngroup by job_type\norder by job_type"
    }
   ]
  }
 ]
}