{
 "title": "Temperatures",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "mercury",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.3.241:9100\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"192.168.3.241:9100\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "venus",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.101:9100\"}[$__interval])",
     "legendFormat": "{{ chip }}  {{ sensor }}"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_crit_celsius{instance=\"192.168.3.101:9100\"} [$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "earth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.214:9100\"}[$__interval])",
     "legendFormat": "{{ chip }}  {{ sensor }}"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_crit_celsius{instance=\"192.168.3.214:9100\"} [$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "mars",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.102:9100\"}[$__interval])",
     "legendFormat": "{{ chip }}  {{ sensor }}"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_crit_celsius{instance=\"192.168.3.102:9100\"} [$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "jupiter",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.219:9100\"}[$__interval])",
     "legendFormat": "{{ chip }}  {{ sensor }}"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_crit_celsius{instance=\"192.168.3.219:9100\"} [$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  }
 ]
}