{
 "title": "Ingress Logs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "geomap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (geoip_latitude, geoip_longitude, geoip_city, geoip_country_code, ip_address, vhost) (count_over_time({k8_app=\"nginx-parsed\"} \n| json \n|__error__=``[$__range]))",
     "legendFormat": "{{ip_address}}"
    }
   ]
  },
  {
   "title": "Request Locations",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (pmessage_geoip_city, pmessage_geoip_region, pmessage_geoip_country_code) (count_over_time({k8_instance=\"nginx-external\"} \n| json \n| pmessage_geoip_country_name != \"\"\n| __error__=\"\" [$__interval]))",
     "legendFormat": "{{pmessage_geoip_city}} {{pmessage_geoip_region}} {{pmessage_geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Top 10 vHosts",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (pmessage_vhost) (count_over_time({k8_instance=\"nginx-external\"} \n| json \n| pmessage_http_user_agent != \"\"\n| __error__=\"\" [$__interval]))",
     "legendFormat": "{{pmessage_vhost}}"
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (pmessage_http_user_agent) (count_over_time({k8_instance=\"nginx-external\"} \n| json \n| pmessage_http_user_agent != \"\"\n| __error__=\"\" [$__interval]))",
     "legendFormat": "{{pmessage_http_user_agent}}"
    }
   ]
  },
  {
   "title": "Request Paths",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (pmessage_vhost,pmessage_path) (count_over_time({k8_instance=\"nginx-external\"} \n| json \n| __error__=\"\" [$__interval]))",
     "legendFormat": "{{pmessage_vhost,pmessage_path}}"
    }
   ]
  },
  {
   "title": "Ingress External Logs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{k8_app=\"nginx-parsed\"} |= `` | json"
    }
   ]
  },
  {
   "title": "External Requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(ingress) (rate(nginx_ingress_controller_requests{service=\"nginx-external-controller-metrics\", ingress!~\"\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Internal Requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(ingress) (rate(nginx_ingress_controller_requests{service=\"nginx-internal-controller-metrics\", ingress!~\"\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Ingress External Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "{k8_app=\"nginx-parsed\"} |= `` | json | line_format `{{.timestamp_}} - {{.status}} - {{.vhost}} - {{.ip_address}} - {{.user_agent}} - {{.geoip_city}}, {{.geoip_region_name}} {{.geoip_country_code}} - {{.path}}`"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "{k8_instance=\"nginx-external\"} | json \n| pmessage_x_forwarded_for !~ `.*192.168.1.*` \n| pmessage_x_forwarded_for !~ `.*10.42.*`\n| message != `\\t`\n| line_format `{{.pmessage_time}} - {{.pmessage_status}} - {{.pmessage_vhost}} - {{.pmessage_x_forwarded_for}} - {{.pmessage_http_user_agent}} - {{.pmessage_geoip_city}}, {{.pmessage_geoip_region_name}} {{.pmessage_geoip_country_code}} - {{.pmessage_path}} - {{.pmessage_http_referrer}}` \n| pmessage_status != \"200\" | pmessage_status != \"204\" \n| __error__=``"
    }
   ]
  },
  {
   "title": "Fulll Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "{k8_instance=\"nginx-external\"} | json \n| pmessage_x_forwarded_for !~ `.*192.168.*` \n| pmessage_x_forwarded_for !~ `.*10.42.*`\n| __error__=``"
    }
   ]
  }
 ]
}