{
 "title": "Temperatures",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "diskstation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.1.2:9100\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"192.168.1.2:9100\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "aurora",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.2.20:9100\"}[$__interval])",
     "legendFormat": "{{ chip }}  {{ sensor }}"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_crit_celsius{instance=\"192.168.2.10:9100\"} [$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "nuc11",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.2.15:9100\"}[$__interval])",
     "legendFormat": "{{ chip }}  {{ sensor }}"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_crit_celsius{instance=\"192.168.2.10:9100\"} [$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "k8s-01 (x51)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.2.10:9100\"}[$__interval])",
     "legendFormat": "{{ chip }}  {{ sensor }}"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_crit_celsius{instance=\"192.168.2.10:9100\"} [$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "k8s-02 (pi4a)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.2.11:9100\"}[$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_crit_celsius{instance=\"192.168.2.11:9100\"} [$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "k8s-03 (pi4b)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.2.12:9100\"}[$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_crit_celsius{instance=\"192.168.2.12:9100\"} [$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "k8s-04 (pi4c)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.2.13:9100\"}[$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_crit_celsius{instance=\"192.168.2.12:9100\"} [$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "k8s-05 (pi4d)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.2.14:9100\"}[$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_crit_celsius{instance=\"192.168.2.18:9100\"} [$__interval])",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  }
 ]
}